name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-bot:
    name: Homebrew Tap Syntax & Formula Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@1f8e202ffddf94def7f42f6fa3a482e821489f9c

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Clean Environment
        run: brew test-bot --only-cleanup-before

      - name: Setup Test Environment
        run: brew test-bot --only-setup

      - name: Validate Tap Syntax & Formula Style
        run: brew test-bot --only-tap-syntax
